// @generated by tools/exiftool-tables/codegen_fits.py; do not edit.
// Source: Image::ExifTool::FITS::Main.

pub(super) static FITS_TAG_NAMES: &[(&str, &str)] = &[
    ("AUTHOR", "Author"),
    ("BACKGRND", "Background"),
    ("COMMENT", "Comment"),
    ("DATE", "CreateDate"),
    ("DATE-END", "ObservationDateEnd"),
    ("DATE-OBS", "ObservationDate"),
    ("HISTORY", "History"),
    ("INSTRUME", "Instrument"),
    ("OBJECT", "Object"),
    ("OBSERVER", "Observer"),
    ("REFERENC", "Reference"),
    ("TELESCOP", "Telescope"),
    ("TIME-END", "ObservationTimeEnd"),
    ("TIME-OBS", "ObservationTime"),
];
