#!/usr/bin/env python3
"""Generate FITS keyword names from ExifTool's FITS Main table."""

import argparse
import json


def rust_string(value):
    return json.dumps(value, ensure_ascii=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("json", help="tables JSON produced by dump_tables.pl")
    parser.add_argument("-o", "--output", required=True)
    args = parser.parse_args()

    with open(args.json, encoding="utf-8") as fh:
        data = json.load(fh)

    try:
        tags = data["modules"]["FITS"]["tables"]["Main"]["tags"]
    except KeyError as exc:
        raise SystemExit(f"ExifTool FITS Main table is missing {exc}") from exc

    names = []
    for keyword, definition in tags.items():
        name = definition.get("Name")
        if not isinstance(name, str):
            raise SystemExit(f"FITS tag {keyword!r} has no scalar Name")
        names.append((keyword, name))

    names.sort()
    lines = [
        "// @generated by tools/exiftool-tables/codegen_fits.py; do not edit.",
        "// Source: Image::ExifTool::FITS::Main.",
        "",
        "pub(super) static FITS_TAG_NAMES: &[(&str, &str)] = &[",
    ]
    lines.extend(
        f"    ({rust_string(keyword)}, {rust_string(name)}),"
        for keyword, name in names
    )
    lines.extend(["];", ""])

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"generated {len(names)} FITS keyword names -> {args.output}")


if __name__ == "__main__":
    main()
