//! ExifTool Composite tag definitions, generated from ExifTool's Perl tables.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables`.
//!
//! Composite tags are derived, not read: `Megapixels` comes from `ImageSize`,
//! which comes from `ImageWidth`/`ImageHeight`. Only the dependency graph is
//! generated here. The arithmetic lives in `super::compute`, is written by
//! hand, and is looked up by name -- a composite with no implementation simply
//! never fires, rather than producing an approximation.

/// One Composite tag: a name and the tags it is derived from.
#[derive(Clone, Copy, Debug)]
pub struct Composite {
    pub name: &'static str,
    /// ExifTool module that defined it, kept for provenance.
    pub module: &'static str,
    pub group2: &'static str,
    /// All of these must be present, in this order, or the tag does not fire.
    pub require: &'static [&'static str],
    /// Optional inputs; absent ones are passed through as `None`.
    pub desire: &'static [&'static str],
}

/// Every Composite definition ExifTool declares (104 total).
pub static COMPOSITES: &[Composite] = &[
    Composite {
        name: "Duration",
        module: "AIFF",
        group2: "Other",
        require: &["AIFF:SampleRate", "AIFF:NumSampleFrames"],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "APE",
        group2: "Audio",
        require: &[
            "APE:SampleRate",
            "APE:TotalFrames",
            "APE:BlocksPerFrame",
            "APE:FinalFrameBlocks",
        ],
        desire: &[],
    },
    Composite {
        name: "RunTimeSincePowerUp",
        module: "Apple",
        group2: "Camera",
        require: &["Apple:RunTimeValue", "Apple:RunTimeScale"],
        desire: &[],
    },
    Composite {
        name: "ConditionalFEC",
        module: "Canon",
        group2: "Camera",
        require: &["FlashExposureComp", "FlashBits"],
        desire: &[],
    },
    Composite {
        name: "DigitalZoom",
        module: "Canon",
        group2: "Camera",
        require: &[
            "Canon:ZoomSourceWidth",
            "Canon:ZoomTargetWidth",
            "Canon:DigitalZoom",
        ],
        desire: &[],
    },
    Composite {
        name: "DriveMode",
        module: "Canon",
        group2: "Camera",
        require: &["ContinuousDrive", "SelfTimer"],
        desire: &[],
    },
    Composite {
        name: "FileNumber",
        module: "Canon",
        group2: "Image",
        require: &["DirectoryIndex", "FileIndex"],
        desire: &[],
    },
    Composite {
        name: "FlashType",
        module: "Canon",
        group2: "Camera",
        require: &["FlashBits"],
        desire: &[],
    },
    Composite {
        name: "ISO",
        module: "Canon",
        group2: "Camera",
        require: &[],
        desire: &["Canon:CameraISO", "Canon:BaseISO", "Canon:AutoISO"],
    },
    Composite {
        name: "Lens",
        module: "Canon",
        group2: "Camera",
        require: &["Canon:MinFocalLength", "Canon:MaxFocalLength"],
        desire: &[],
    },
    Composite {
        name: "Lens35efl",
        module: "Canon",
        group2: "Camera",
        require: &["Canon:MinFocalLength", "Canon:MaxFocalLength", "Lens"],
        desire: &["ScaleFactor35efl"],
    },
    Composite {
        name: "OriginalDecisionData",
        module: "Canon",
        group2: "Camera",
        require: &["OriginalDecisionDataOffset"],
        desire: &[],
    },
    Composite {
        name: "RedEyeReduction",
        module: "Canon",
        group2: "Camera",
        require: &["CanonFlashMode", "FlashBits"],
        desire: &[],
    },
    Composite {
        name: "ShootingMode",
        module: "Canon",
        group2: "Camera",
        require: &["CanonExposureMode", "EasyMode"],
        desire: &["BulbDuration"],
    },
    Composite {
        name: "ShutterCurtainHack",
        module: "Canon",
        group2: "Camera",
        require: &["FlashBits"],
        desire: &["ShutterCurtainSync"],
    },
    Composite {
        name: "WB_RGGBLevels",
        module: "Canon",
        group2: "Camera",
        require: &["Canon:WhiteBalance"],
        desire: &[
            "WB_RGGBLevelsAsShot",
            "WB_RGGBLevelsAuto",
            "WB_RGGBLevelsDaylight",
            "WB_RGGBLevelsCloudy",
            "WB_RGGBLevelsTungsten",
            "WB_RGGBLevelsFluorescent",
            "WB_RGGBLevelsFlash",
            "WB_RGGBLevelsCustom",
            "WB_RGGBLevelsShade",
            "WB_RGGBLevelsKelvin",
        ],
    },
    Composite {
        name: "Aperture",
        module: "Exif",
        group2: "Image",
        require: &[],
        desire: &["FNumber", "ApertureValue"],
    },
    Composite {
        name: "BlueBalance",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            "WB_RGGBLevels",
            "WB_RGBGLevels",
            "WB_RBGGLevels",
            "WB_GRBGLevels",
            "WB_GRGBLevels",
            "WB_GBRGLevels",
            "WB_RGBLevels",
            "WB_GRBLevels",
            "WB_RBLevels",
            "WBBlueLevel",
            "WBGreenLevel",
        ],
    },
    Composite {
        name: "CFAPattern",
        module: "Exif",
        group2: "Image",
        require: &["CFARepeatPatternDim", "CFAPattern2"],
        desire: &[],
    },
    Composite {
        name: "CircleOfConfusion",
        module: "Exif",
        group2: "Camera",
        require: &["ScaleFactor35efl"],
        desire: &[],
    },
    Composite {
        name: "DOF",
        module: "Exif",
        group2: "Image",
        require: &["FocalLength", "Aperture", "CircleOfConfusion"],
        desire: &[
            "FocusDistance",
            "SubjectDistance",
            "ObjectDistance",
            "ApproximateFocusDistance",
            "FocusDistanceLower",
            "FocusDistanceUpper",
        ],
    },
    Composite {
        name: "DateTimeOriginal",
        module: "Exif",
        group2: "Time",
        require: &[],
        desire: &["DateTimeCreated", "DateCreated", "TimeCreated"],
    },
    Composite {
        name: "FOV",
        module: "Exif",
        group2: "Image",
        require: &["FocalLength", "ScaleFactor35efl"],
        desire: &["FocusDistance"],
    },
    Composite {
        name: "FocalLength35efl",
        module: "Exif",
        group2: "Camera",
        require: &["FocalLength"],
        desire: &["ScaleFactor35efl"],
    },
    Composite {
        name: "GPSPosition",
        module: "Exif",
        group2: "Location",
        require: &["GPSLatitude", "GPSLongitude"],
        desire: &[],
    },
    Composite {
        name: "HyperfocalDistance",
        module: "Exif",
        group2: "Camera",
        require: &["FocalLength", "Aperture", "CircleOfConfusion"],
        desire: &[],
    },
    Composite {
        name: "ImageSize",
        module: "Exif",
        group2: "Image",
        require: &["ImageWidth", "ImageHeight"],
        desire: &["ExifImageWidth", "ExifImageHeight", "RawImageCroppedSize"],
    },
    Composite {
        name: "JpgFromRaw",
        module: "Exif",
        group2: "Preview",
        require: &["JpgFromRawStart", "JpgFromRawLength"],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "Exif",
        group2: "Camera",
        require: &["LensType"],
        desire: &[
            "FocalLength",
            "MaxAperture",
            "MaxApertureValue",
            "MinFocalLength",
            "MaxFocalLength",
            "LensModel",
            "LensFocalRange",
            "LensSpec",
            "LensType2",
            "LensType3",
            "LensFocalLength",
            "RFLensType",
        ],
    },
    Composite {
        name: "LightValue",
        module: "Exif",
        group2: "Image",
        require: &["Aperture", "ShutterSpeed", "ISO"],
        desire: &[],
    },
    Composite {
        name: "Megapixels",
        module: "Exif",
        group2: "Image",
        require: &["ImageSize"],
        desire: &[],
    },
    Composite {
        name: "OtherImage",
        module: "Exif",
        group2: "Preview",
        require: &["OtherImageStart", "OtherImageLength"],
        desire: &["OtherImageStart (1)", "OtherImageLength (1)"],
    },
    Composite {
        name: "PreviewImage",
        module: "Exif",
        group2: "Preview",
        require: &["PreviewImageStart", "PreviewImageLength"],
        desire: &[
            "PreviewImageValid",
            "PreviewImageStart (1)",
            "PreviewImageLength (1)",
        ],
    },
    Composite {
        name: "PreviewImageSize",
        module: "Exif",
        group2: "Image",
        require: &["PreviewImageWidth", "PreviewImageHeight"],
        desire: &[],
    },
    Composite {
        name: "PreviewJXL",
        module: "Exif",
        group2: "Preview",
        require: &["PreviewJXLStart", "PreviewJXLLength"],
        desire: &["PreviewJXLStart (1)", "PreviewJXLLength (1)"],
    },
    Composite {
        name: "RedBalance",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            "WB_RGGBLevels",
            "WB_RGBGLevels",
            "WB_RBGGLevels",
            "WB_GRBGLevels",
            "WB_GRGBLevels",
            "WB_GBRGLevels",
            "WB_RGBLevels",
            "WB_GRBLevels",
            "WB_RBLevels",
            "WBRedLevel",
            "WBGreenLevel",
        ],
    },
    Composite {
        name: "ScaleFactor35efl",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            "FocalLength",
            "FocalLengthIn35mmFormat",
            "Composite:DigitalZoom",
            "FocalPlaneDiagonal",
            "SensorSize",
            "FocalPlaneXSize",
            "FocalPlaneYSize",
            "FocalPlaneResolutionUnit",
            "FocalPlaneXResolution",
            "FocalPlaneYResolution",
            "ExifImageWidth",
            "ExifImageHeight",
            "CanonImageWidth",
            "CanonImageHeight",
            "ImageWidth",
            "ImageHeight",
        ],
    },
    Composite {
        name: "ShutterSpeed",
        module: "Exif",
        group2: "Image",
        require: &[],
        desire: &["ExposureTime", "ShutterSpeedValue", "BulbDuration"],
    },
    Composite {
        name: "SubSecCreateDate",
        module: "Exif",
        group2: "Time",
        require: &["EXIF:CreateDate"],
        desire: &["SubSecTimeDigitized", "OffsetTimeDigitized"],
    },
    Composite {
        name: "SubSecDateTimeOriginal",
        module: "Exif",
        group2: "Time",
        require: &["EXIF:DateTimeOriginal"],
        desire: &["SubSecTimeOriginal", "OffsetTimeOriginal"],
    },
    Composite {
        name: "SubSecModifyDate",
        module: "Exif",
        group2: "Time",
        require: &["EXIF:ModifyDate"],
        desire: &["SubSecTime", "OffsetTime"],
    },
    Composite {
        name: "ThumbnailImage",
        module: "Exif",
        group2: "Preview",
        require: &["ThumbnailOffset", "ThumbnailLength"],
        desire: &[],
    },
    Composite {
        name: "ThumbnailTIFF",
        module: "Exif",
        group2: "Preview",
        require: &[
            "SubfileType",
            "Compression",
            "ImageWidth",
            "ImageHeight",
            "BitsPerSample",
            "PhotometricInterpretation",
            "StripOffsets",
            "SamplesPerPixel",
            "RowsPerStrip",
            "StripByteCounts",
        ],
        desire: &["PlanarConfiguration", "Orientation"],
    },
    Composite {
        name: "Duration",
        module: "FLAC",
        group2: "Other",
        require: &["FLAC:SampleRate", "FLAC:TotalSamples"],
        desire: &[],
    },
    Composite {
        name: "PeakSpectralSensitivity",
        module: "FLIR",
        group2: "Camera",
        require: &["FLIR:PlanckB"],
        desire: &[],
    },
    Composite {
        name: "PreviewImage",
        module: "FlashPix",
        group2: "Preview",
        require: &["ScreenNail"],
        desire: &[],
    },
    Composite {
        name: "GPSAltitude",
        module: "GPS",
        group2: "Location",
        require: &[],
        desire: &[
            "GPS:GPSAltitude",
            "GPS:GPSAltitudeRef",
            "XMP:GPSAltitude",
            "XMP:GPSAltitudeRef",
        ],
    },
    Composite {
        name: "GPSDateTime",
        module: "GPS",
        group2: "Time",
        require: &["GPS:GPSDateStamp", "GPS:GPSTimeStamp"],
        desire: &[],
    },
    Composite {
        name: "GPSDestLatitude",
        module: "GPS",
        group2: "Location",
        require: &["GPS:GPSDestLatitude", "GPS:GPSDestLatitudeRef"],
        desire: &[],
    },
    Composite {
        name: "GPSDestLongitude",
        module: "GPS",
        group2: "Location",
        require: &["GPS:GPSDestLongitude", "GPS:GPSDestLongitudeRef"],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "GPS",
        group2: "Location",
        require: &["GPS:GPSLatitude", "GPS:GPSLatitudeRef"],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "GPS",
        group2: "Location",
        require: &["GPS:GPSLongitude", "GPS:GPSLongitudeRef"],
        desire: &[],
    },
    Composite {
        name: "DateTimeOriginal",
        module: "ID3",
        group2: "Time",
        require: &[],
        desire: &["ID3:RecordingTime", "ID3:Year", "ID3:Date", "ID3:Time"],
    },
    Composite {
        name: "DateTimeCreated",
        module: "IPTC",
        group2: "Time",
        require: &["IPTC:DateCreated", "IPTC:TimeCreated"],
        desire: &[],
    },
    Composite {
        name: "DigitalCreationDateTime",
        module: "IPTC",
        group2: "Time",
        require: &["IPTC:DigitalCreationDate", "IPTC:DigitalCreationTime"],
        desire: &[],
    },
    Composite {
        name: "VolumeSize",
        module: "ISO",
        group2: "Other",
        require: &["ISO:VolumeBlockCount", "ISO:VolumeBlockSize"],
        desire: &[],
    },
    Composite {
        name: "DateCreated",
        module: "Kodak",
        group2: "Time",
        require: &["Kodak:YearCreated", "Kodak:MonthDayCreated"],
        desire: &[],
    },
    Composite {
        name: "WB_RGBLevels",
        module: "Kodak",
        group2: "Camera",
        require: &["KDC_IFD:WhiteBalance"],
        desire: &[
            "WB_RGBLevelsAuto",
            "WB_RGBLevelsFluorescent",
            "WB_RGBLevelsTungsten",
            "WB_RGBLevelsDaylight",
            "WB_RGBLevels4",
            "WB_RGBLevels5",
            "WB_RGBLevelsShade",
        ],
    },
    Composite {
        name: "AudioBitrate",
        module: "MPEG",
        group2: "Audio",
        require: &[
            "MPEG:MPEGAudioVersion",
            "MPEG:SampleRate",
            "MPEG:VBRBytes",
            "MPEG:VBRFrames",
        ],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "MPEG",
        group2: "Video",
        require: &["FileSize"],
        desire: &[
            "ID3Size",
            "MPEG:AudioBitrate",
            "MPEG:VideoBitrate",
            "MPEG:VBRFrames",
            "MPEG:SampleRate",
            "MPEG:MPEGAudioVersion",
        ],
    },
    Composite {
        name: "MPImage",
        module: "MPF",
        group2: "Preview",
        require: &["MPImageStart", "MPImageLength", "MPImageType"],
        desire: &[],
    },
    Composite {
        name: "AutoFocus",
        module: "Nikon",
        group2: "Camera",
        require: &["Nikon:FocusMode"],
        desire: &[],
    },
    Composite {
        name: "ContrastDetectAF",
        module: "Nikon",
        group2: "Camera",
        require: &["Nikon:FocusMode", "Nikon:AFDetectionMethod"],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "Nikon",
        group2: "Camera",
        require: &[
            "Nikon:LensIDNumber",
            "LensFStops",
            "MinFocalLength",
            "MaxFocalLength",
            "MaxApertureAtMinFocal",
            "MaxApertureAtMaxFocal",
            "MCUVersion",
            "Nikon:LensType",
        ],
        desire: &[],
    },
    Composite {
        name: "LensSpec",
        module: "Nikon",
        group2: "Camera",
        require: &["Nikon:Lens", "Nikon:LensType"],
        desire: &[],
    },
    Composite {
        name: "PhaseDetectAF",
        module: "Nikon",
        group2: "Camera",
        require: &["Nikon:FocusPointSchema", "Nikon:AFDetectionMethod"],
        desire: &[],
    },
    Composite {
        name: "ExtenderStatus",
        module: "Olympus",
        group2: "Camera",
        require: &["Olympus:Extender", "Olympus:LensType", "MaxApertureValue"],
        desire: &[],
    },
    Composite {
        name: "LensType",
        module: "Olympus",
        group2: "Camera",
        require: &["LensTypeMake", "LensTypeModel"],
        desire: &[],
    },
    Composite {
        name: "ZoomedPreviewImage",
        module: "Olympus",
        group2: "Preview",
        require: &["ZoomedPreviewStart", "ZoomedPreviewLength"],
        desire: &[],
    },
    Composite {
        name: "AdvancedSceneMode",
        module: "Panasonic",
        group2: "Camera",
        require: &["Model", "SceneMode", "AdvancedSceneType"],
        desire: &[],
    },
    Composite {
        name: "ImageHeight",
        module: "PanasonicRaw",
        group2: "Other",
        require: &["IFD0:SensorTopBorder", "IFD0:SensorBottomBorder"],
        desire: &[],
    },
    Composite {
        name: "ImageWidth",
        module: "PanasonicRaw",
        group2: "Other",
        require: &["IFD0:SensorLeftBorder", "IFD0:SensorRightBorder"],
        desire: &[],
    },
    Composite {
        name: "GPSDateTime",
        module: "Parrot",
        group2: "Time",
        require: &["Parrot:GPSLatitude", "Main:CreateDate", "SampleTime"],
        desire: &[],
    },
    Composite {
        name: "ImageHeight",
        module: "PostScript",
        group2: "Image",
        require: &[],
        desire: &["Main:PostScript:ImageData", "PostScript:BoundingBox"],
    },
    Composite {
        name: "ImageWidth",
        module: "PostScript",
        group2: "Image",
        require: &[],
        desire: &["Main:PostScript:ImageData", "PostScript:BoundingBox"],
    },
    Composite {
        name: "AvgBitrate",
        module: "QuickTime",
        group2: "Video",
        require: &["QuickTime::MediaDataSize", "QuickTime::Duration"],
        desire: &[],
    },
    Composite {
        name: "CDDBDiscPlayTime",
        module: "QuickTime",
        group2: "Audio",
        require: &["CDDB1Info"],
        desire: &[],
    },
    Composite {
        name: "CDDBDiscTracks",
        module: "QuickTime",
        group2: "Audio",
        require: &["CDDB1Info"],
        desire: &[],
    },
    Composite {
        name: "GPSAltitude",
        module: "QuickTime",
        group2: "Location",
        require: &["QuickTime:GPSCoordinates"],
        desire: &[],
    },
    Composite {
        name: "GPSAltitudeRef",
        module: "QuickTime",
        group2: "Location",
        require: &["QuickTime:GPSCoordinates"],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "QuickTime",
        group2: "Location",
        require: &["QuickTime:GPSCoordinates"],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "QuickTime",
        group2: "Location",
        require: &["QuickTime:GPSCoordinates"],
        desire: &[],
    },
    Composite {
        name: "Rotation",
        module: "QuickTime",
        group2: "Video",
        require: &["QuickTime:MatrixStructure", "QuickTime:HandlerType"],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "RIFF",
        group2: "Other",
        require: &["RIFF:FrameRate", "RIFF:FrameCount"],
        desire: &["VideoFrameRate", "VideoFrameCount"],
    },
    Composite {
        name: "LensID",
        module: "Ricoh",
        group2: "Camera",
        require: &["Ricoh:LensFirmware"],
        desire: &[],
    },
    Composite {
        name: "RicohPitch",
        module: "Ricoh",
        group2: "Camera",
        require: &["Ricoh:Accelerometer"],
        desire: &[],
    },
    Composite {
        name: "RicohRoll",
        module: "Ricoh",
        group2: "Camera",
        require: &["Ricoh:Accelerometer"],
        desire: &[],
    },
    Composite {
        name: "DepthMapTiff",
        module: "Samsung",
        group2: "Image",
        require: &["DepthMapData", "DepthMapWidth", "DepthMapHeight"],
        desire: &[],
    },
    Composite {
        name: "SingleShotDepthMapTiff",
        module: "Samsung",
        group2: "Image",
        require: &["SingleShotDepthMap", "SegWidth", "SegHeight"],
        desire: &[],
    },
    Composite {
        name: "WB_RGGBLevels",
        module: "Samsung",
        group2: "Image",
        require: &["WB_RGGBLevelsUncorrected", "WB_RGGBLevelsBlack"],
        desire: &[],
    },
    Composite {
        name: "FocusDistance",
        module: "Sony",
        group2: "Camera",
        require: &["Sony:FocusPosition", "FocalLength"],
        desire: &[],
    },
    Composite {
        name: "FocusDistance2",
        module: "Sony",
        group2: "Camera",
        require: &["Sony:FocusPosition2", "FocalLengthIn35mmFormat"],
        desire: &[],
    },
    Composite {
        name: "GPSDateTime",
        module: "Sony",
        group2: "Time",
        require: &["Sony:GPSDateStamp", "Sony:GPSTimeStamp"],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "Sony",
        group2: "Location",
        require: &["Sony:GPSLatitude", "Sony:GPSLatitudeRef"],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "Sony",
        group2: "Location",
        require: &["Sony:GPSLongitude", "Sony:GPSLongitudeRef"],
        desire: &[],
    },
    Composite {
        name: "HiddenData",
        module: "Sony",
        group2: "Camera",
        require: &["Sony:HiddenDataOffset", "Sony:HiddenDataLength"],
        desire: &[],
    },
    Composite {
        name: "IDCPreviewImage",
        module: "SonyIDC",
        group2: "Preview",
        require: &["IDCPreviewStart", "IDCPreviewLength"],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "Vorbis",
        group2: "Other",
        require: &["Vorbis:NominalBitrate", "FileSize"],
        desire: &[],
    },
    Composite {
        name: "Flash",
        module: "XMP",
        group2: "Camera",
        require: &[],
        desire: &[
            "XMP:FlashFired",
            "XMP:FlashReturn",
            "XMP:FlashMode",
            "XMP:FlashFunction",
            "XMP:FlashRedEyeMode",
            "XMP:Flash",
        ],
    },
    Composite {
        name: "GPSDestLatitudeRef",
        module: "XMP",
        group2: "Location",
        require: &["XMP-exif:GPSDestLatitude"],
        desire: &[],
    },
    Composite {
        name: "GPSDestLongitudeRef",
        module: "XMP",
        group2: "Location",
        require: &["XMP-exif:GPSDestLongitude"],
        desire: &[],
    },
    Composite {
        name: "GPSLatitudeRef",
        module: "XMP",
        group2: "Location",
        require: &["XMP-exif:GPSLatitude"],
        desire: &[],
    },
    Composite {
        name: "GPSLongitudeRef",
        module: "XMP",
        group2: "Location",
        require: &["XMP-exif:GPSLongitude"],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "XMP",
        group2: "Camera",
        require: &["XMP-aux:LensID", "Make"],
        desire: &["LensInfo", "FocalLength", "LensModel", "MaxApertureValue"],
    },
];
