//! ExifTool Composite tag definitions, generated from ExifTool's Perl tables.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables`.
//!
//! Composite tags are derived, not read: `Megapixels` comes from `ImageSize`,
//! which comes from `ImageWidth`/`ImageHeight`. Only the dependency graph is
//! generated here. The arithmetic lives in `super::compute`, is written by
//! hand, and is looked up by name -- a composite with no implementation simply
//! never fires, rather than producing an approximation.

/// One Composite tag: a name and the tags it is derived from.
#[derive(Clone, Copy, Debug)]
pub struct Composite {
    pub name: &'static str,
    /// ExifTool module that defined it, kept for provenance.
    pub module: &'static str,
    pub group2: &'static str,
    /// All of these indexed inputs must be present or the tag does not fire.
    pub require: &'static [(usize, &'static str)],
    /// Indexed optional inputs; absent positions are passed through as `None`.
    pub desire: &'static [(usize, &'static str)],
}

/// Every Composite definition ExifTool declares (104 total).
pub static COMPOSITES: &[Composite] = &[
    Composite {
        name: "Duration",
        module: "AIFF",
        group2: "Other",
        require: &[(0, "AIFF:SampleRate"), (1, "AIFF:NumSampleFrames")],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "APE",
        group2: "Audio",
        require: &[
            (0, "APE:SampleRate"),
            (1, "APE:TotalFrames"),
            (2, "APE:BlocksPerFrame"),
            (3, "APE:FinalFrameBlocks"),
        ],
        desire: &[],
    },
    Composite {
        name: "RunTimeSincePowerUp",
        module: "Apple",
        group2: "Camera",
        require: &[(0, "Apple:RunTimeValue"), (1, "Apple:RunTimeScale")],
        desire: &[],
    },
    Composite {
        name: "ConditionalFEC",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "FlashExposureComp"), (1, "FlashBits")],
        desire: &[],
    },
    Composite {
        name: "DigitalZoom",
        module: "Canon",
        group2: "Camera",
        require: &[
            (0, "Canon:ZoomSourceWidth"),
            (1, "Canon:ZoomTargetWidth"),
            (2, "Canon:DigitalZoom"),
        ],
        desire: &[],
    },
    Composite {
        name: "DriveMode",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "ContinuousDrive"), (1, "SelfTimer")],
        desire: &[],
    },
    Composite {
        name: "FileNumber",
        module: "Canon",
        group2: "Image",
        require: &[(0, "DirectoryIndex"), (1, "FileIndex")],
        desire: &[],
    },
    Composite {
        name: "FlashType",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "FlashBits")],
        desire: &[],
    },
    Composite {
        name: "ISO",
        module: "Canon",
        group2: "Camera",
        require: &[],
        desire: &[
            (0, "Canon:CameraISO"),
            (1, "Canon:BaseISO"),
            (2, "Canon:AutoISO"),
        ],
    },
    Composite {
        name: "Lens",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "Canon:MinFocalLength"), (1, "Canon:MaxFocalLength")],
        desire: &[],
    },
    Composite {
        name: "Lens35efl",
        module: "Canon",
        group2: "Camera",
        require: &[
            (0, "Canon:MinFocalLength"),
            (1, "Canon:MaxFocalLength"),
            (3, "Lens"),
        ],
        desire: &[(2, "ScaleFactor35efl")],
    },
    Composite {
        name: "OriginalDecisionData",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "OriginalDecisionDataOffset")],
        desire: &[],
    },
    Composite {
        name: "RedEyeReduction",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "CanonFlashMode"), (1, "FlashBits")],
        desire: &[],
    },
    Composite {
        name: "ShootingMode",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "CanonExposureMode"), (1, "EasyMode")],
        desire: &[(2, "BulbDuration")],
    },
    Composite {
        name: "ShutterCurtainHack",
        module: "Canon",
        group2: "Camera",
        require: &[(1, "FlashBits")],
        desire: &[(0, "ShutterCurtainSync")],
    },
    Composite {
        name: "WB_RGGBLevels",
        module: "Canon",
        group2: "Camera",
        require: &[(0, "Canon:WhiteBalance")],
        desire: &[
            (1, "WB_RGGBLevelsAsShot"),
            (2, "WB_RGGBLevelsAuto"),
            (3, "WB_RGGBLevelsDaylight"),
            (4, "WB_RGGBLevelsCloudy"),
            (5, "WB_RGGBLevelsTungsten"),
            (6, "WB_RGGBLevelsFluorescent"),
            (7, "WB_RGGBLevelsFlash"),
            (8, "WB_RGGBLevelsCustom"),
            (10, "WB_RGGBLevelsShade"),
            (11, "WB_RGGBLevelsKelvin"),
        ],
    },
    Composite {
        name: "Aperture",
        module: "Exif",
        group2: "Image",
        require: &[],
        desire: &[(0, "FNumber"), (1, "ApertureValue")],
    },
    Composite {
        name: "BlueBalance",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            (0, "WB_RGGBLevels"),
            (1, "WB_RGBGLevels"),
            (2, "WB_RBGGLevels"),
            (3, "WB_GRBGLevels"),
            (4, "WB_GRGBLevels"),
            (5, "WB_GBRGLevels"),
            (6, "WB_RGBLevels"),
            (7, "WB_GRBLevels"),
            (8, "WB_RBLevels"),
            (9, "WBBlueLevel"),
            (10, "WBGreenLevel"),
        ],
    },
    Composite {
        name: "CFAPattern",
        module: "Exif",
        group2: "Image",
        require: &[(0, "CFARepeatPatternDim"), (1, "CFAPattern2")],
        desire: &[],
    },
    Composite {
        name: "CircleOfConfusion",
        module: "Exif",
        group2: "Camera",
        require: &[(0, "ScaleFactor35efl")],
        desire: &[],
    },
    Composite {
        name: "DOF",
        module: "Exif",
        group2: "Image",
        require: &[
            (0, "FocalLength"),
            (1, "Aperture"),
            (2, "CircleOfConfusion"),
        ],
        desire: &[
            (3, "FocusDistance"),
            (4, "SubjectDistance"),
            (5, "ObjectDistance"),
            (6, "ApproximateFocusDistance"),
            (7, "FocusDistanceLower"),
            (8, "FocusDistanceUpper"),
        ],
    },
    Composite {
        name: "DateTimeOriginal",
        module: "Exif",
        group2: "Time",
        require: &[],
        desire: &[
            (0, "DateTimeCreated"),
            (1, "DateCreated"),
            (2, "TimeCreated"),
        ],
    },
    Composite {
        name: "FOV",
        module: "Exif",
        group2: "Image",
        require: &[(0, "FocalLength"), (1, "ScaleFactor35efl")],
        desire: &[(2, "FocusDistance")],
    },
    Composite {
        name: "FocalLength35efl",
        module: "Exif",
        group2: "Camera",
        require: &[(0, "FocalLength")],
        desire: &[(1, "ScaleFactor35efl")],
    },
    Composite {
        name: "GPSPosition",
        module: "Exif",
        group2: "Location",
        require: &[(0, "GPSLatitude"), (1, "GPSLongitude")],
        desire: &[],
    },
    Composite {
        name: "HyperfocalDistance",
        module: "Exif",
        group2: "Camera",
        require: &[
            (0, "FocalLength"),
            (1, "Aperture"),
            (2, "CircleOfConfusion"),
        ],
        desire: &[],
    },
    Composite {
        name: "ImageSize",
        module: "Exif",
        group2: "Image",
        require: &[(0, "ImageWidth"), (1, "ImageHeight")],
        desire: &[
            (2, "ExifImageWidth"),
            (3, "ExifImageHeight"),
            (4, "RawImageCroppedSize"),
        ],
    },
    Composite {
        name: "JpgFromRaw",
        module: "Exif",
        group2: "Preview",
        require: &[(0, "JpgFromRawStart"), (1, "JpgFromRawLength")],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "Exif",
        group2: "Camera",
        require: &[(0, "LensType")],
        desire: &[
            (1, "FocalLength"),
            (2, "MaxAperture"),
            (3, "MaxApertureValue"),
            (4, "MinFocalLength"),
            (5, "MaxFocalLength"),
            (6, "LensModel"),
            (7, "LensFocalRange"),
            (8, "LensSpec"),
            (9, "LensType2"),
            (10, "LensType3"),
            (11, "LensFocalLength"),
            (12, "RFLensType"),
        ],
    },
    Composite {
        name: "LightValue",
        module: "Exif",
        group2: "Image",
        require: &[(0, "Aperture"), (1, "ShutterSpeed"), (2, "ISO")],
        desire: &[],
    },
    Composite {
        name: "Megapixels",
        module: "Exif",
        group2: "Image",
        require: &[(0, "ImageSize")],
        desire: &[],
    },
    Composite {
        name: "OtherImage",
        module: "Exif",
        group2: "Preview",
        require: &[(0, "OtherImageStart"), (1, "OtherImageLength")],
        desire: &[(2, "OtherImageStart (1)"), (3, "OtherImageLength (1)")],
    },
    Composite {
        name: "PreviewImage",
        module: "Exif",
        group2: "Preview",
        require: &[(0, "PreviewImageStart"), (1, "PreviewImageLength")],
        desire: &[
            (2, "PreviewImageValid"),
            (3, "PreviewImageStart (1)"),
            (4, "PreviewImageLength (1)"),
        ],
    },
    Composite {
        name: "PreviewImageSize",
        module: "Exif",
        group2: "Image",
        require: &[(0, "PreviewImageWidth"), (1, "PreviewImageHeight")],
        desire: &[],
    },
    Composite {
        name: "PreviewJXL",
        module: "Exif",
        group2: "Preview",
        require: &[(0, "PreviewJXLStart"), (1, "PreviewJXLLength")],
        desire: &[(2, "PreviewJXLStart (1)"), (3, "PreviewJXLLength (1)")],
    },
    Composite {
        name: "RedBalance",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            (0, "WB_RGGBLevels"),
            (1, "WB_RGBGLevels"),
            (2, "WB_RBGGLevels"),
            (3, "WB_GRBGLevels"),
            (4, "WB_GRGBLevels"),
            (5, "WB_GBRGLevels"),
            (6, "WB_RGBLevels"),
            (7, "WB_GRBLevels"),
            (8, "WB_RBLevels"),
            (9, "WBRedLevel"),
            (10, "WBGreenLevel"),
        ],
    },
    Composite {
        name: "ScaleFactor35efl",
        module: "Exif",
        group2: "Camera",
        require: &[],
        desire: &[
            (0, "FocalLength"),
            (1, "FocalLengthIn35mmFormat"),
            (2, "Composite:DigitalZoom"),
            (3, "FocalPlaneDiagonal"),
            (4, "SensorSize"),
            (5, "FocalPlaneXSize"),
            (6, "FocalPlaneYSize"),
            (7, "FocalPlaneResolutionUnit"),
            (8, "FocalPlaneXResolution"),
            (9, "FocalPlaneYResolution"),
            (10, "ExifImageWidth"),
            (11, "ExifImageHeight"),
            (12, "CanonImageWidth"),
            (13, "CanonImageHeight"),
            (14, "ImageWidth"),
            (15, "ImageHeight"),
        ],
    },
    Composite {
        name: "ShutterSpeed",
        module: "Exif",
        group2: "Image",
        require: &[],
        desire: &[
            (0, "ExposureTime"),
            (1, "ShutterSpeedValue"),
            (2, "BulbDuration"),
        ],
    },
    Composite {
        name: "SubSecCreateDate",
        module: "Exif",
        group2: "Time",
        require: &[(0, "EXIF:CreateDate")],
        desire: &[(1, "SubSecTimeDigitized"), (2, "OffsetTimeDigitized")],
    },
    Composite {
        name: "SubSecDateTimeOriginal",
        module: "Exif",
        group2: "Time",
        require: &[(0, "EXIF:DateTimeOriginal")],
        desire: &[(1, "SubSecTimeOriginal"), (2, "OffsetTimeOriginal")],
    },
    Composite {
        name: "SubSecModifyDate",
        module: "Exif",
        group2: "Time",
        require: &[(0, "EXIF:ModifyDate")],
        desire: &[(1, "SubSecTime"), (2, "OffsetTime")],
    },
    Composite {
        name: "ThumbnailImage",
        module: "Exif",
        group2: "Preview",
        require: &[(0, "ThumbnailOffset"), (1, "ThumbnailLength")],
        desire: &[],
    },
    Composite {
        name: "ThumbnailTIFF",
        module: "Exif",
        group2: "Preview",
        require: &[
            (0, "SubfileType"),
            (1, "Compression"),
            (2, "ImageWidth"),
            (3, "ImageHeight"),
            (4, "BitsPerSample"),
            (5, "PhotometricInterpretation"),
            (6, "StripOffsets"),
            (7, "SamplesPerPixel"),
            (8, "RowsPerStrip"),
            (9, "StripByteCounts"),
        ],
        desire: &[(10, "PlanarConfiguration"), (11, "Orientation")],
    },
    Composite {
        name: "Duration",
        module: "FLAC",
        group2: "Other",
        require: &[(0, "FLAC:SampleRate"), (1, "FLAC:TotalSamples")],
        desire: &[],
    },
    Composite {
        name: "PeakSpectralSensitivity",
        module: "FLIR",
        group2: "Camera",
        require: &[(0, "FLIR:PlanckB")],
        desire: &[],
    },
    Composite {
        name: "PreviewImage",
        module: "FlashPix",
        group2: "Preview",
        require: &[(0, "ScreenNail")],
        desire: &[],
    },
    Composite {
        name: "GPSAltitude",
        module: "GPS",
        group2: "Location",
        require: &[],
        desire: &[
            (0, "GPS:GPSAltitude"),
            (1, "GPS:GPSAltitudeRef"),
            (2, "XMP:GPSAltitude"),
            (3, "XMP:GPSAltitudeRef"),
        ],
    },
    Composite {
        name: "GPSDateTime",
        module: "GPS",
        group2: "Time",
        require: &[(0, "GPS:GPSDateStamp"), (1, "GPS:GPSTimeStamp")],
        desire: &[],
    },
    Composite {
        name: "GPSDestLatitude",
        module: "GPS",
        group2: "Location",
        require: &[(0, "GPS:GPSDestLatitude"), (1, "GPS:GPSDestLatitudeRef")],
        desire: &[],
    },
    Composite {
        name: "GPSDestLongitude",
        module: "GPS",
        group2: "Location",
        require: &[(0, "GPS:GPSDestLongitude"), (1, "GPS:GPSDestLongitudeRef")],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "GPS",
        group2: "Location",
        require: &[(0, "GPS:GPSLatitude"), (1, "GPS:GPSLatitudeRef")],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "GPS",
        group2: "Location",
        require: &[(0, "GPS:GPSLongitude"), (1, "GPS:GPSLongitudeRef")],
        desire: &[],
    },
    Composite {
        name: "DateTimeOriginal",
        module: "ID3",
        group2: "Time",
        require: &[],
        desire: &[
            (0, "ID3:RecordingTime"),
            (1, "ID3:Year"),
            (2, "ID3:Date"),
            (3, "ID3:Time"),
        ],
    },
    Composite {
        name: "DateTimeCreated",
        module: "IPTC",
        group2: "Time",
        require: &[(0, "IPTC:DateCreated"), (1, "IPTC:TimeCreated")],
        desire: &[],
    },
    Composite {
        name: "DigitalCreationDateTime",
        module: "IPTC",
        group2: "Time",
        require: &[
            (0, "IPTC:DigitalCreationDate"),
            (1, "IPTC:DigitalCreationTime"),
        ],
        desire: &[],
    },
    Composite {
        name: "VolumeSize",
        module: "ISO",
        group2: "Other",
        require: &[(0, "ISO:VolumeBlockCount"), (1, "ISO:VolumeBlockSize")],
        desire: &[],
    },
    Composite {
        name: "DateCreated",
        module: "Kodak",
        group2: "Time",
        require: &[(0, "Kodak:YearCreated"), (1, "Kodak:MonthDayCreated")],
        desire: &[],
    },
    Composite {
        name: "WB_RGBLevels",
        module: "Kodak",
        group2: "Camera",
        require: &[(0, "KDC_IFD:WhiteBalance")],
        desire: &[
            (1, "WB_RGBLevelsAuto"),
            (2, "WB_RGBLevelsFluorescent"),
            (3, "WB_RGBLevelsTungsten"),
            (4, "WB_RGBLevelsDaylight"),
            (5, "WB_RGBLevels4"),
            (6, "WB_RGBLevels5"),
            (7, "WB_RGBLevelsShade"),
        ],
    },
    Composite {
        name: "AudioBitrate",
        module: "MPEG",
        group2: "Audio",
        require: &[
            (0, "MPEG:MPEGAudioVersion"),
            (1, "MPEG:SampleRate"),
            (2, "MPEG:VBRBytes"),
            (3, "MPEG:VBRFrames"),
        ],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "MPEG",
        group2: "Video",
        require: &[(0, "FileSize")],
        desire: &[
            (1, "ID3Size"),
            (2, "MPEG:AudioBitrate"),
            (3, "MPEG:VideoBitrate"),
            (4, "MPEG:VBRFrames"),
            (5, "MPEG:SampleRate"),
            (6, "MPEG:MPEGAudioVersion"),
        ],
    },
    Composite {
        name: "MPImage",
        module: "MPF",
        group2: "Preview",
        require: &[
            (0, "MPImageStart"),
            (1, "MPImageLength"),
            (2, "MPImageType"),
        ],
        desire: &[],
    },
    Composite {
        name: "AutoFocus",
        module: "Nikon",
        group2: "Camera",
        require: &[(0, "Nikon:FocusMode")],
        desire: &[],
    },
    Composite {
        name: "ContrastDetectAF",
        module: "Nikon",
        group2: "Camera",
        require: &[(0, "Nikon:FocusMode"), (1, "Nikon:AFDetectionMethod")],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "Nikon",
        group2: "Camera",
        require: &[
            (0, "Nikon:LensIDNumber"),
            (1, "LensFStops"),
            (2, "MinFocalLength"),
            (3, "MaxFocalLength"),
            (4, "MaxApertureAtMinFocal"),
            (5, "MaxApertureAtMaxFocal"),
            (6, "MCUVersion"),
            (7, "Nikon:LensType"),
        ],
        desire: &[],
    },
    Composite {
        name: "LensSpec",
        module: "Nikon",
        group2: "Camera",
        require: &[(0, "Nikon:Lens"), (1, "Nikon:LensType")],
        desire: &[],
    },
    Composite {
        name: "PhaseDetectAF",
        module: "Nikon",
        group2: "Camera",
        require: &[
            (0, "Nikon:FocusPointSchema"),
            (1, "Nikon:AFDetectionMethod"),
        ],
        desire: &[],
    },
    Composite {
        name: "ExtenderStatus",
        module: "Olympus",
        group2: "Camera",
        require: &[
            (0, "Olympus:Extender"),
            (1, "Olympus:LensType"),
            (2, "MaxApertureValue"),
        ],
        desire: &[],
    },
    Composite {
        name: "LensType",
        module: "Olympus",
        group2: "Camera",
        require: &[(0, "LensTypeMake"), (1, "LensTypeModel")],
        desire: &[],
    },
    Composite {
        name: "ZoomedPreviewImage",
        module: "Olympus",
        group2: "Preview",
        require: &[(0, "ZoomedPreviewStart"), (1, "ZoomedPreviewLength")],
        desire: &[],
    },
    Composite {
        name: "AdvancedSceneMode",
        module: "Panasonic",
        group2: "Camera",
        require: &[(0, "Model"), (1, "SceneMode"), (2, "AdvancedSceneType")],
        desire: &[],
    },
    Composite {
        name: "ImageHeight",
        module: "PanasonicRaw",
        group2: "Other",
        require: &[(0, "IFD0:SensorTopBorder"), (1, "IFD0:SensorBottomBorder")],
        desire: &[],
    },
    Composite {
        name: "ImageWidth",
        module: "PanasonicRaw",
        group2: "Other",
        require: &[(0, "IFD0:SensorLeftBorder"), (1, "IFD0:SensorRightBorder")],
        desire: &[],
    },
    Composite {
        name: "GPSDateTime",
        module: "Parrot",
        group2: "Time",
        require: &[
            (0, "Parrot:GPSLatitude"),
            (1, "Main:CreateDate"),
            (2, "SampleTime"),
        ],
        desire: &[],
    },
    Composite {
        name: "ImageHeight",
        module: "PostScript",
        group2: "Image",
        require: &[],
        desire: &[
            (0, "Main:PostScript:ImageData"),
            (1, "PostScript:BoundingBox"),
        ],
    },
    Composite {
        name: "ImageWidth",
        module: "PostScript",
        group2: "Image",
        require: &[],
        desire: &[
            (0, "Main:PostScript:ImageData"),
            (1, "PostScript:BoundingBox"),
        ],
    },
    Composite {
        name: "AvgBitrate",
        module: "QuickTime",
        group2: "Video",
        require: &[(0, "QuickTime::MediaDataSize"), (1, "QuickTime::Duration")],
        desire: &[],
    },
    Composite {
        name: "CDDBDiscPlayTime",
        module: "QuickTime",
        group2: "Audio",
        require: &[(0, "CDDB1Info")],
        desire: &[],
    },
    Composite {
        name: "CDDBDiscTracks",
        module: "QuickTime",
        group2: "Audio",
        require: &[(0, "CDDB1Info")],
        desire: &[],
    },
    Composite {
        name: "GPSAltitude",
        module: "QuickTime",
        group2: "Location",
        require: &[(0, "QuickTime:GPSCoordinates")],
        desire: &[],
    },
    Composite {
        name: "GPSAltitudeRef",
        module: "QuickTime",
        group2: "Location",
        require: &[(0, "QuickTime:GPSCoordinates")],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "QuickTime",
        group2: "Location",
        require: &[(0, "QuickTime:GPSCoordinates")],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "QuickTime",
        group2: "Location",
        require: &[(0, "QuickTime:GPSCoordinates")],
        desire: &[],
    },
    Composite {
        name: "Rotation",
        module: "QuickTime",
        group2: "Video",
        require: &[
            (0, "QuickTime:MatrixStructure"),
            (1, "QuickTime:HandlerType"),
        ],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "RIFF",
        group2: "Other",
        require: &[(0, "RIFF:FrameRate"), (1, "RIFF:FrameCount")],
        desire: &[(2, "VideoFrameRate"), (3, "VideoFrameCount")],
    },
    Composite {
        name: "LensID",
        module: "Ricoh",
        group2: "Camera",
        require: &[(0, "Ricoh:LensFirmware")],
        desire: &[],
    },
    Composite {
        name: "RicohPitch",
        module: "Ricoh",
        group2: "Camera",
        require: &[(0, "Ricoh:Accelerometer")],
        desire: &[],
    },
    Composite {
        name: "RicohRoll",
        module: "Ricoh",
        group2: "Camera",
        require: &[(0, "Ricoh:Accelerometer")],
        desire: &[],
    },
    Composite {
        name: "DepthMapTiff",
        module: "Samsung",
        group2: "Image",
        require: &[
            (0, "DepthMapData"),
            (1, "DepthMapWidth"),
            (2, "DepthMapHeight"),
        ],
        desire: &[],
    },
    Composite {
        name: "SingleShotDepthMapTiff",
        module: "Samsung",
        group2: "Image",
        require: &[(0, "SingleShotDepthMap"), (1, "SegWidth"), (2, "SegHeight")],
        desire: &[],
    },
    Composite {
        name: "WB_RGGBLevels",
        module: "Samsung",
        group2: "Image",
        require: &[(0, "WB_RGGBLevelsUncorrected"), (1, "WB_RGGBLevelsBlack")],
        desire: &[],
    },
    Composite {
        name: "FocusDistance",
        module: "Sony",
        group2: "Camera",
        require: &[(0, "Sony:FocusPosition"), (1, "FocalLength")],
        desire: &[],
    },
    Composite {
        name: "FocusDistance2",
        module: "Sony",
        group2: "Camera",
        require: &[(0, "Sony:FocusPosition2"), (1, "FocalLengthIn35mmFormat")],
        desire: &[],
    },
    Composite {
        name: "GPSDateTime",
        module: "Sony",
        group2: "Time",
        require: &[(0, "Sony:GPSDateStamp"), (1, "Sony:GPSTimeStamp")],
        desire: &[],
    },
    Composite {
        name: "GPSLatitude",
        module: "Sony",
        group2: "Location",
        require: &[(0, "Sony:GPSLatitude"), (1, "Sony:GPSLatitudeRef")],
        desire: &[],
    },
    Composite {
        name: "GPSLongitude",
        module: "Sony",
        group2: "Location",
        require: &[(0, "Sony:GPSLongitude"), (1, "Sony:GPSLongitudeRef")],
        desire: &[],
    },
    Composite {
        name: "HiddenData",
        module: "Sony",
        group2: "Camera",
        require: &[(0, "Sony:HiddenDataOffset"), (1, "Sony:HiddenDataLength")],
        desire: &[],
    },
    Composite {
        name: "IDCPreviewImage",
        module: "SonyIDC",
        group2: "Preview",
        require: &[(0, "IDCPreviewStart"), (1, "IDCPreviewLength")],
        desire: &[],
    },
    Composite {
        name: "Duration",
        module: "Vorbis",
        group2: "Other",
        require: &[(0, "Vorbis:NominalBitrate"), (1, "FileSize")],
        desire: &[],
    },
    Composite {
        name: "Flash",
        module: "XMP",
        group2: "Camera",
        require: &[],
        desire: &[
            (0, "XMP:FlashFired"),
            (1, "XMP:FlashReturn"),
            (2, "XMP:FlashMode"),
            (3, "XMP:FlashFunction"),
            (4, "XMP:FlashRedEyeMode"),
            (5, "XMP:Flash"),
        ],
    },
    Composite {
        name: "GPSDestLatitudeRef",
        module: "XMP",
        group2: "Location",
        require: &[(0, "XMP-exif:GPSDestLatitude")],
        desire: &[],
    },
    Composite {
        name: "GPSDestLongitudeRef",
        module: "XMP",
        group2: "Location",
        require: &[(0, "XMP-exif:GPSDestLongitude")],
        desire: &[],
    },
    Composite {
        name: "GPSLatitudeRef",
        module: "XMP",
        group2: "Location",
        require: &[(0, "XMP-exif:GPSLatitude")],
        desire: &[],
    },
    Composite {
        name: "GPSLongitudeRef",
        module: "XMP",
        group2: "Location",
        require: &[(0, "XMP-exif:GPSLongitude")],
        desire: &[],
    },
    Composite {
        name: "LensID",
        module: "XMP",
        group2: "Camera",
        require: &[(0, "XMP-aux:LensID"), (1, "Make")],
        desire: &[
            (2, "LensInfo"),
            (3, "FocalLength"),
            (4, "LensModel"),
            (5, "MaxApertureValue"),
        ],
    },
];
